__all__ = ['authenticate',
           'authorize',
           'auto_authorize',
           'set_error',
           'set_prompt',
           'set_timeout',
           'send',
           'sendline',
           'exec',
           'execline',
           'wait_for']
